CREATE TABLE `patents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(512) NOT NULL,
	`titleEn` varchar(512),
	`patentNumber` varchar(128),
	`applicants` text,
	`inventors` text,
	`abstract` text,
	`summary` text,
	`patentType` enum('invention','utility','design','pct') NOT NULL DEFAULT 'invention',
	`country` varchar(128) NOT NULL DEFAULT 'CN',
	`status` enum('pending','granted','rejected','expired') NOT NULL DEFAULT 'pending',
	`ipcCode` varchar(256),
	`sourceUrl` varchar(1024),
	`tags` text,
	`isHighlight` boolean NOT NULL DEFAULT false,
	`filedAt` timestamp,
	`publishedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `patents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `research_papers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(512) NOT NULL,
	`titleEn` varchar(512),
	`authors` text,
	`abstract` text,
	`summary` text,
	`journal` varchar(256),
	`doi` varchar(256),
	`sourceUrl` varchar(1024),
	`imageUrl` varchar(1024),
	`researchType` enum('efficiency','stability','materials','fabrication','tandem','flexible','commercialization','other') NOT NULL DEFAULT 'other',
	`keyFindings` text,
	`institutions` text,
	`tags` text,
	`isHighlight` boolean NOT NULL DEFAULT false,
	`publishedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `research_papers_id` PRIMARY KEY(`id`)
);
