/**
 * Seed script for 30 major global perovskite PV manufacturers
 * Data sourced from: perovskite-info.com, company official websites, industry reports (2024-2025)
 */

export const manufacturerSeedData = [
  // ===== FEATURED - CHUNHUO OPTOELECTRONICS (PINNED FIRST) =====
  {
    name: "湖州市鹑火光电有限公司",
    nameEn: "Huzhou Chunhuo Optoelectronics Co., Ltd.",
    country: "中国",
    region: "亚太",
    foundedYear: 2021,
    stage: "量产",
    website: "https://www.chunhuopv.com",
    description: "湖州市鹑火光电有限公司成立于2021年6月，总部位于浙江省湖州市德清县，是一家专注于钙钛矿光伏材料、电池组件制备技术及相关高端装备设计研发的高新技术企业，拥有员工80余人。公司核心团队包含两位国家特聘专家、多位省级特聘专家，掌握多项行业领先的光伏技术。公司是目前行业内少数可提供钙钛矿单结和叠层组件整线方案的设备供应商，允许客户自带材料进行全流程打样制备成组件并接受第三方机构认证。2024年12月，鹑火光电首条钙钛矿/晶硅叠层整线设备成功出货，标志着公司正式进入量产阶段。截至2026年1月，公司已完成B+轮融资，投资方包括聚信发展、宜宾人才基金、港信资管等。",
    mainProducts: "钙钛矿太阳能电池核心工艺设备（磁控溅射PVD设备、狭缝涂布设备、原子层沉积ALD设备、激光划刻设备）、钙钛矿单结整线设备、钙钛矿/晶硅叠层整线设备、高效晶硅XBC太阳能电池设备",
    techAchievements: "单结钙钛矿整线设备量产转化效率18%-20%；钙钛矿/晶硅叠层电池量产转化效率超31%；首条钙钛矿/晶硅叠层整线设备2024年12月成功出货；申请多项钙钛矿薄膜制备方法专利（CN121487476A、CN121038557A、CN121487475A等）；建立光伏实验中心对高校及科研院所开放",
    employees: "80+",
    latestEfficiency: 31.0,
    isPinned: true,
    sortOrder: 1,
    tags: ["设备供应商", "叠层整线", "量产设备", "B+轮", "鹑火FL"],
  },
  // ===== CHINA - LEADING COMPANIES =====
  {
    name: "协鑫光电 (GCL Perovskite)",
    nameEn: "GCL Perovskite (Microquanta parent)",
    country: "中国",
    region: "亚太",
    foundedYear: 2019,
    stage: "量产",
    website: "https://www.gcl-perovskite.com",
    description: "昆山协鑫光电材料有限公司成立于2019年底，专注于钙钛矿太阳能组件的研发、生产，为市场提供1m×2m尺寸的大面积钙钛矿光伏组件，量产效率突破19%，是全球钙钛矿组件量产规模最大的企业之一。",
    mainProducts: "大面积钙钛矿光伏组件（1m×2m），GW级产线",
    techAchievements: "1m×2m量产效率>19%，通过IEC61215/IEC61730认证，GW级产线建设中",
    employees: "500+",
    latestEfficiency: 19.0,
    tags: ["量产", "大面积组件", "GW级"],
  },
  {
    name: "纤纳光电 (Microquanta Semiconductor)",
    nameEn: "Microquanta Semiconductor",
    country: "中国",
    region: "亚太",
    foundedYear: 2015,
    stage: "量产",
    website: "https://www.microquanta.com",
    description: "纤纳光电成立于2015年，总部位于杭州，是全球首家实现第三代钙钛矿光伏组件量产的机构，通过多项全球首个IEC全序列稳定性国内外双认证，完成全球首个商业化钙钛矿光伏电站建设。",
    mainProducts: "钙钛矿光伏组件，商业化电站",
    techAchievements: "全球首家实现钙钛矿组件量产，全球首个商业化钙钛矿电站（1MW），IEC全序列认证",
    employees: "300+",
    latestEfficiency: 18.0,
    tags: ["量产", "商业化", "首家"],
  },
  {
    name: "极电光能 (Jike Energy)",
    nameEn: "Jike Energy (UtmoLight)",
    country: "中国",
    region: "亚太",
    foundedYear: 2020,
    stage: "量产",
    website: "http://www.utmolight.com",
    description: "极电光能起源于长城控股集团，2018年开始钙钛矿技术研发，2020年4月落地无锡。公司在钙钛矿技术研发和产业化方面均处于行业领先地位，1.2m×0.6m单节组件效率达18.2%，并通过IEC61215/IEC61730测试。",
    mainProducts: "钙钛矿光伏组件，叠层电池",
    techAchievements: "1.2m×0.6m单节组件效率18.2%，通过IEC61215/IEC61730测试",
    employees: "400+",
    latestEfficiency: 18.2,
    tags: ["量产", "叠层", "IEC认证"],
  },
  {
    name: "仁烁光能 (Renshine Solar)",
    nameEn: "Renshine Solar",
    country: "中国",
    region: "亚太",
    foundedYear: 2021,
    stage: "中试",
    website: "https://www.renshinesolar.com",
    description: "仁烁光能成立于2021年底，由南京大学谭海仁教授创办，专注高效率钙钛矿光伏电池的研发与制造。连续11次创造钙钛矿电池光电转换效率的世界纪录，已申请核心专利120余项。",
    mainProducts: "全钙钛矿叠层电池，高效率钙钛矿组件",
    techAchievements: "全钙钛矿叠层电池效率30.1%（NREL认证，2024年世界纪录），连续11次刷新世界纪录",
    employees: "200+",
    latestEfficiency: 30.1,
    tags: ["世界纪录", "叠层", "全钙钛矿"],
  },
  {
    name: "黑晶光电",
    nameEn: "Heliasol",
    country: "中国",
    region: "亚太",
    foundedYear: 2019,
    stage: "中试",
    website: "https://www.heliasol.cn",
    description: "黑晶光电成立于2019年，专注于钙钛矿叠层电池技术的研发与生产，研发的串联型钙钛矿/PERC叠层电池转换效率达到行业领先水平，是国内主要的钙钛矿叠层电池研发企业。",
    mainProducts: "钙钛矿/PERC叠层电池，钙钛矿/晶硅叠层组件",
    techAchievements: "钙钛矿/PERC叠层电池效率突破行业领先水平",
    employees: "150+",
    latestEfficiency: 28.5,
    tags: ["叠层", "PERC", "晶硅叠层"],
  },
  {
    name: "曜能光电 (Yaoneng Technology)",
    nameEn: "Yaoneng Technology",
    country: "中国",
    region: "亚太",
    foundedYear: 2017,
    stage: "中试",
    website: "https://www.yaoneng.com",
    description: "北京曜能科技有限公司成立于2017年，是全球最早进行钙钛矿太阳能电池产业化探索的企业之一，专注于钙钛矿/晶硅叠层光伏技术，能够与晶硅技术深度结合，突破传统晶硅效率上限。",
    mainProducts: "钙钛矿/晶硅叠层光伏组件",
    techAchievements: "全球最早进行钙钛矿产业化探索的企业之一，钙钛矿/晶硅叠层技术领先",
    employees: "100+",
    latestEfficiency: 27.0,
    tags: ["叠层", "晶硅叠层", "早期先驱"],
  },
  {
    name: "北京曜能 (Beijing Yaoneng)",
    nameEn: "Beijing Auner Technology",
    country: "中国",
    region: "亚太",
    foundedYear: 2017,
    stage: "研发",
    website: "https://www.auner.cn",
    description: "北京曜能科技（Auner）成立于2017年，专注于钙钛矿/晶硅叠层太阳能电池的研发与产业化，是国内最早布局钙钛矿叠层技术的企业之一。",
    mainProducts: "钙钛矿/晶硅叠层电池",
    techAchievements: "钙钛矿/晶硅叠层技术研发领先",
    employees: "80+",
    latestEfficiency: 26.0,
    tags: ["叠层", "研发"],
  },
  {
    name: "隆基绿能 (LONGi Green Energy)",
    nameEn: "LONGi Green Energy",
    country: "中国",
    region: "亚太",
    foundedYear: 2000,
    stage: "量产",
    website: "https://www.longi.com",
    description: "隆基绿能是全球最大的太阳能科技公司之一，在钙钛矿/晶硅叠层领域创造了多项世界纪录。2025年4月，经NREL认证，其晶硅-钙钛矿叠层电池效率达34.85%，再次刷新世界纪录。",
    mainProducts: "晶硅-钙钛矿叠层电池，单晶硅组件，BC电池",
    techAchievements: "晶硅-钙钛矿叠层电池效率34.85%（NREL认证，2025年世界纪录），2024年34.6%",
    employees: "50000+",
    latestEfficiency: 34.85,
    tags: ["世界纪录", "叠层", "晶硅叠层", "上市公司"],
  },
  {
    name: "天合光能 (Trina Solar)",
    nameEn: "Trina Solar",
    country: "中国",
    region: "亚太",
    foundedYear: 1997,
    stage: "研发",
    website: "https://www.trinasolar.com",
    description: "天合光能是全球领先的光伏组件制造商，积极布局钙钛矿全场景应用，在钙钛矿/晶硅叠层技术研发方面持续投入，致力于将钙钛矿技术商业化。",
    mainProducts: "钙钛矿/晶硅叠层电池，Vertex系列组件",
    techAchievements: "钙钛矿全场景应用研发，叠层技术持续突破",
    employees: "30000+",
    latestEfficiency: 28.0,
    tags: ["叠层", "上市公司", "全场景"],
  },
  {
    name: "晶科能源 (JinkoSolar)",
    nameEn: "JinkoSolar",
    country: "中国",
    region: "亚太",
    foundedYear: 2006,
    stage: "研发",
    website: "https://www.jinkosolar.com",
    description: "晶科能源是全球最大的太阳能组件制造商之一，积极布局TOPCon+钙钛矿叠层技术，致力于实现钙钛矿叠层技术的商业化量产。",
    mainProducts: "TOPCon+钙钛矿叠层电池，Tiger系列组件",
    techAchievements: "TOPCon+钙钛矿叠层商业化研发，效率持续提升",
    employees: "40000+",
    latestEfficiency: 28.5,
    tags: ["叠层", "TOPCon", "上市公司"],
  },

  // ===== EUROPE =====
  {
    name: "Oxford PV",
    nameEn: "Oxford PV",
    country: "英国/德国",
    region: "欧洲",
    foundedYear: 2010,
    stage: "量产",
    website: "https://www.oxfordpv.com",
    description: "Oxford PV是钙钛矿太阳能电池领域的全球领导者，由牛津大学Henry Snaith教授联合创立。公司专注于钙钛矿/硅叠层技术，在德国建有量产工厂，单节钙钛矿/硅叠层电池效率达到28%以上。",
    mainProducts: "钙钛矿/硅叠层太阳能电池，商业化叠层组件",
    techAchievements: "钙钛矿/硅叠层电池效率28%+，德国量产工厂，多项世界纪录保持者",
    employees: "300+",
    latestEfficiency: 28.6,
    tags: ["量产", "叠层", "欧洲领先"],
  },
  {
    name: "Saule Technologies",
    nameEn: "Saule Technologies",
    country: "波兰",
    region: "欧洲",
    foundedYear: 2014,
    stage: "量产",
    website: "https://sauletech.com",
    description: "Saule Technologies是一家波兰高科技公司，开发基于钙钛矿材料的创新太阳能电池。公司率先将喷墨打印技术用于钙钛矿太阳能电池制造，生产超薄、柔性的建筑一体化光伏产品。",
    mainProducts: "喷墨打印钙钛矿太阳能电池，柔性BIPV产品",
    techAchievements: "全球首家喷墨打印钙钛矿电池量产，BIPV建筑一体化应用",
    employees: "150+",
    latestEfficiency: 17.0,
    tags: ["喷墨打印", "柔性", "BIPV", "量产"],
  },
  {
    name: "Solaronix",
    nameEn: "Solaronix",
    country: "瑞士",
    region: "欧洲",
    foundedYear: 1993,
    stage: "量产",
    website: "https://www.solaronix.com",
    description: "Solaronix是瑞士领先的太阳能材料和设备供应商，专注于染料敏化太阳能电池（DSSC）和钙钛矿太阳能电池的材料开发与商业化，为研究机构和工业客户提供高质量的光伏材料。",
    mainProducts: "钙钛矿太阳能电池材料，DSSC材料，光伏设备",
    techAchievements: "30年光伏材料研发经验，钙钛矿材料商业化供应",
    employees: "50+",
    latestEfficiency: 15.0,
    tags: ["材料供应", "DSSC", "商业化"],
  },
  {
    name: "HZB (亥姆霍兹柏林研究中心)",
    nameEn: "Helmholtz-Zentrum Berlin (HZB)",
    country: "德国",
    region: "欧洲",
    foundedYear: 2008,
    stage: "研发",
    website: "https://www.helmholtz-berlin.de",
    description: "亥姆霍兹柏林研究中心（HZB）是德国领先的能源材料研究机构，在钙钛矿/硅叠层太阳能电池领域创造了多项世界纪录，2022年实现32.5%的钙钛矿/硅叠层效率世界纪录。",
    mainProducts: "钙钛矿/硅叠层太阳能电池研究，高效率光伏材料",
    techAchievements: "2022年钙钛矿/硅叠层效率32.5%世界纪录（NREL认证）",
    employees: "1000+",
    latestEfficiency: 32.5,
    tags: ["研究机构", "世界纪录", "叠层"],
  },
  {
    name: "EPFL (洛桑联邦理工学院)",
    nameEn: "EPFL - École Polytechnique Fédérale de Lausanne",
    country: "瑞士",
    region: "欧洲",
    foundedYear: 1969,
    stage: "研发",
    website: "https://www.epfl.ch",
    description: "EPFL是全球顶尖的钙钛矿太阳能电池研究机构，由Michael Grätzel教授领导的团队在钙钛矿电池基础研究方面做出了开创性贡献，多次创造单结钙钛矿电池效率世界纪录。",
    mainProducts: "高效率钙钛矿太阳能电池，钙钛矿材料研究",
    techAchievements: "多项单结钙钛矿电池效率世界纪录，钙钛矿电池基础研究开创者",
    employees: "500+",
    latestEfficiency: 26.1,
    tags: ["研究机构", "世界纪录", "基础研究"],
  },

  // ===== USA =====
  {
    name: "Swift Solar",
    nameEn: "Swift Solar",
    country: "美国",
    region: "北美",
    foundedYear: 2017,
    stage: "中试",
    website: "https://www.swiftsolar.com",
    description: "Swift Solar是一家美国太阳能技术公司，专注于构建高性能全钙钛矿叠层产品。公司使命是释放太阳能的全部潜力，通过全钙钛矿叠层技术实现超越硅基电池的效率。",
    mainProducts: "全钙钛矿叠层太阳能电池，柔性钙钛矿电池",
    techAchievements: "全钙钛矿叠层技术研发，柔性钙钛矿电池开发",
    employees: "50+",
    latestEfficiency: 27.0,
    tags: ["全钙钛矿叠层", "柔性", "美国"],
  },
  {
    name: "Tandem PV",
    nameEn: "Tandem PV",
    country: "美国",
    region: "北美",
    foundedYear: 2019,
    stage: "中试",
    website: "https://www.tandempv.com",
    description: "Tandem PV（前身为Iris PV）是美国钙钛矿叠层太阳能电池公司，生产效率29%的叠层钙钛矿面板，比普通硅太阳能面板功率高出30%以上，致力于实现钙钛矿叠层组件的商业化量产。",
    mainProducts: "钙钛矿/硅叠层太阳能面板（29%效率）",
    techAchievements: "29%效率叠层钙钛矿面板，比普通硅面板功率高30%+",
    employees: "80+",
    latestEfficiency: 29.0,
    tags: ["叠层", "商业化", "美国"],
  },
  {
    name: "CubicPV",
    nameEn: "CubicPV",
    country: "美国",
    region: "北美",
    foundedYear: 2021,
    stage: "研发",
    website: "https://cubicpv.com",
    description: "CubicPV由Hunt Perovskite Technologies和1366 Technologies合并成立，是美国专注于下一代太阳能组件设计的公司，致力于通过提高效率来延续太阳能LCOE降低的时代。",
    mainProducts: "钙钛矿叠层太阳能组件，高效硅基底",
    techAchievements: "Hunt Perovskite Technologies与1366 Technologies技术整合",
    employees: "100+",
    latestEfficiency: 27.5,
    tags: ["叠层", "美国", "合并"],
  },
  {
    name: "BlueDot Photonics",
    nameEn: "BlueDot Photonics",
    country: "美国",
    region: "北美",
    foundedYear: 2020,
    stage: "研发",
    website: "https://www.bluedotphotonics.com",
    description: "BlueDot Photonics是美国一家专注于钙钛矿光子学的公司，利用钙钛矿材料的独特光学特性开发新型光伏和光子器件，在钙钛矿量子点和发光器件领域有重要研究成果。",
    mainProducts: "钙钛矿光子器件，钙钛矿量子点",
    techAchievements: "钙钛矿光子学创新技术",
    employees: "30+",
    latestEfficiency: 22.0,
    tags: ["光子学", "量子点", "美国"],
  },
  {
    name: "NREL (美国国家可再生能源实验室)",
    nameEn: "National Renewable Energy Laboratory (NREL)",
    country: "美国",
    region: "北美",
    foundedYear: 1977,
    stage: "研发",
    website: "https://www.nrel.gov",
    description: "NREL是美国能源部下属的国家可再生能源实验室，是全球最权威的太阳能电池效率认证机构，同时也是钙钛矿太阳能电池的重要研究机构，维护全球最权威的太阳能电池效率记录表。",
    mainProducts: "太阳能电池效率认证，钙钛矿电池研究",
    techAchievements: "全球最权威效率认证机构，钙钛矿/硅叠层效率33.7%（与KAUST合作）",
    employees: "3000+",
    latestEfficiency: 33.7,
    tags: ["研究机构", "认证机构", "权威"],
  },

  // ===== ASIA-PACIFIC (non-China) =====
  {
    name: "KAUST (阿卜杜拉国王科技大学)",
    nameEn: "King Abdullah University of Science and Technology (KAUST)",
    country: "沙特阿拉伯",
    region: "中东",
    foundedYear: 2009,
    stage: "研发",
    website: "https://www.kaust.edu.sa",
    description: "KAUST是全球顶尖的钙钛矿太阳能电池研究机构，与NREL合作创造了多项效率世界纪录。其研究团队在钙钛矿/硅叠层电池领域取得了突破性进展，推动了全球钙钛矿技术的发展。",
    mainProducts: "高效率钙钛矿/硅叠层电池，钙钛矿材料研究",
    techAchievements: "与NREL合作创造钙钛矿/硅叠层效率33.7%世界纪录",
    employees: "2000+",
    latestEfficiency: 33.7,
    tags: ["研究机构", "世界纪录", "叠层"],
  },
  {
    name: "Panasonic (松下)",
    nameEn: "Panasonic Corporation",
    country: "日本",
    region: "亚太",
    foundedYear: 1918,
    stage: "研发",
    website: "https://www.panasonic.com",
    description: "松下是全球知名的电子和能源公司，在钙钛矿太阳能电池领域有重要研究投入，特别是在稳定性和耐久性方面取得了重要进展，致力于将钙钛矿技术与HIT电池技术相结合。",
    mainProducts: "钙钛矿/HIT叠层电池，HIT太阳能电池",
    techAchievements: "钙钛矿稳定性研究领先，HIT+钙钛矿叠层技术",
    employees: "240000+",
    latestEfficiency: 24.0,
    tags: ["叠层", "HIT", "日本", "上市公司"],
  },
  {
    name: "Sharp (夏普)",
    nameEn: "Sharp Corporation",
    country: "日本",
    region: "亚太",
    foundedYear: 1912,
    stage: "研发",
    website: "https://global.sharp",
    description: "夏普是日本领先的电子和太阳能公司，在钙钛矿太阳能电池研究方面有重要投入，特别是在大面积钙钛矿组件和稳定性改进方面取得了重要进展。",
    mainProducts: "钙钛矿太阳能电池，大面积组件",
    techAchievements: "大面积钙钛矿组件研发，稳定性改进",
    employees: "50000+",
    latestEfficiency: 23.5,
    tags: ["大面积", "日本", "上市公司"],
  },

  // ===== MORE CHINESE COMPANIES =====
  {
    name: "中来股份 (Jolywood)",
    nameEn: "Jolywood (Suzhou) Sunwatt",
    country: "中国",
    region: "亚太",
    foundedYear: 2010,
    stage: "研发",
    website: "https://www.jolywood.cn",
    description: "中来股份是中国领先的N型太阳能电池和组件制造商，积极布局钙钛矿叠层技术，致力于将钙钛矿与TOPCon技术结合，实现更高效率的叠层太阳能组件。",
    mainProducts: "钙钛矿/TOPCon叠层电池，N型TOPCon组件",
    techAchievements: "钙钛矿/TOPCon叠层技术研发",
    employees: "5000+",
    latestEfficiency: 27.0,
    tags: ["叠层", "TOPCon", "上市公司"],
  },
  {
    name: "钧达股份 (Junda)",
    nameEn: "Junda Solar",
    country: "中国",
    region: "亚太",
    foundedYear: 2012,
    stage: "研发",
    website: "https://www.junda-solar.com",
    description: "钧达股份是中国重要的太阳能电池制造商，积极布局钙钛矿技术，在钙钛矿电池研发方面持续投入，致力于实现钙钛矿电池的规模化量产。",
    mainProducts: "钙钛矿太阳能电池，HJT电池",
    techAchievements: "钙钛矿电池研发布局，HJT+钙钛矿叠层探索",
    employees: "8000+",
    latestEfficiency: 26.0,
    tags: ["研发", "HJT", "上市公司"],
  },
  {
    name: "迈为股份 (Maysun Solar)",
    nameEn: "Maysun Solar Technology",
    country: "中国",
    region: "亚太",
    foundedYear: 2010,
    stage: "研发",
    website: "https://www.maysun-solar.com",
    description: "迈为股份是中国领先的太阳能设备制造商，在钙钛矿设备领域有重要布局，为钙钛矿电池量产提供关键设备支持，是钙钛矿产业链中重要的设备供应商。",
    mainProducts: "钙钛矿生产设备，HJT生产线设备",
    techAchievements: "钙钛矿设备龙头，为多家钙钛矿企业提供设备支持",
    employees: "3000+",
    latestEfficiency: null,
    tags: ["设备", "上市公司", "产业链"],
  },
  {
    name: "苏州大学 (Soochow University)",
    nameEn: "Soochow University - Perovskite Research",
    country: "中国",
    region: "亚太",
    foundedYear: 1900,
    stage: "研发",
    website: "https://www.suda.edu.cn",
    description: "苏州大学是中国领先的钙钛矿太阳能电池研究机构，与澳大利亚新南威尔士大学合作，于2025年创造了单结钙钛矿电池效率26.95%的世界纪录（NREL认证）。",
    mainProducts: "高效率单结钙钛矿太阳能电池研究",
    techAchievements: "单结钙钛矿电池效率26.95%世界纪录（NREL认证，2025年）",
    employees: "3000+",
    latestEfficiency: 26.95,
    tags: ["研究机构", "世界纪录", "单结"],
  },
  {
    name: "南京大学 (Nanjing University)",
    nameEn: "Nanjing University - Tan Hairen Group",
    country: "中国",
    region: "亚太",
    foundedYear: 1902,
    stage: "研发",
    website: "https://www.nju.edu.cn",
    description: "南京大学谭海仁教授团队是全球全钙钛矿叠层电池领域的领军研究团队，与仁烁光能合作创造了全钙钛矿叠层电池效率30.1%的世界纪录（NREL认证，2024年），并于2025年进一步突破。",
    mainProducts: "全钙钛矿叠层太阳能电池研究",
    techAchievements: "全钙钛矿叠层效率30.1%世界纪录（NREL认证），钙钛矿组件效率17.2%世界纪录",
    employees: "5000+",
    latestEfficiency: 30.1,
    tags: ["研究机构", "世界纪录", "全钙钛矿叠层"],
  },
  {
    name: "中国科学技术大学 (USTC)",
    nameEn: "University of Science and Technology of China (USTC)",
    country: "中国",
    region: "亚太",
    foundedYear: 1958,
    stage: "研发",
    website: "https://www.ustc.edu.cn",
    description: "中国科学技术大学是中国顶尖的钙钛矿太阳能电池研究机构，徐集贤教授团队于2024年创造了单结钙钛矿电池稳态效率26.7%的世界纪录（NREL认证）。",
    mainProducts: "高效率单结钙钛矿太阳能电池研究",
    techAchievements: "单结钙钛矿电池稳态效率26.7%世界纪录（NREL认证，2024年）",
    employees: "5000+",
    latestEfficiency: 26.7,
    tags: ["研究机构", "世界纪录", "单结"],
  },
  {
    name: "安徽光山光伏 (Guangshan PV)",
    nameEn: "Anhui Guangshan Photovoltaic",
    country: "中国",
    region: "亚太",
    foundedYear: 2022,
    stage: "中试",
    website: "https://www.guangshanpv.com",
    description: "安徽光山光伏是中国新兴的钙钛矿光伏企业，专注于钙钛矿组件的研发和中试生产，致力于推动钙钛矿光伏技术的商业化应用。",
    mainProducts: "钙钛矿光伏组件",
    techAchievements: "钙钛矿组件中试生产",
    employees: "100+",
    latestEfficiency: 17.0,
    tags: ["中试", "组件"],
  },
];

export const totalManufacturers = manufacturerSeedData.length;
