import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
dotenv.config();

const conn = await mysql.createConnection(process.env.DATABASE_URL);

// 删除所有示例数据
await conn.query('DELETE FROM tenders');
console.log('Cleared all existing tenders.');

// 真实抓取的钙钛矿招投标信息（来源：采招网、北极星光伏网、上海有色网、中国国际招标网等）
const tenders = [
  {
    title: '华能清能院库布齐二期钙钛矿光伏组件设备招标（中标公示）',
    description: '华能清能院库布齐沙漠南部新能源基地光伏先导工程二期光伏实证基地钙钛矿组件设备招标中标结果公布。中标人：昆山协鑫光电材料有限公司，中标价格2,309,874元，单价2.046元/W。本次招标采购钙钛矿组件3528块，峰值功率320Wp，尺寸2005mm×1005mm，共计1.12896MWp。交货地点：内蒙古自治区鄂尔多斯市杭锦旗吉日嘎朗图镇华能库布齐沙漠南部新能源基地。',
    projectType: 'procurement',
    budget: '230.99万元（中标价2.046元/W）',
    region: '内蒙古自治区鄂尔多斯市',
    publisherName: '中国华能集团清洁能源技术研究院有限公司',
    contactInfo: '北京市昌平区北七家镇未来科学城华能创新基地实验楼A楼',
    sourceUrl: 'https://news.smm.cn/news/103291846',
    sourcePlatform: '上海有色网（北极星太阳能光伏网）',
    isImportant: true,
    status: 'awarded',
    publishedAt: new Date('2025-04-21'),
  },
  {
    title: '华能清能院钙钛矿光伏组件设备招标（纤纳光电、极电光能等3家入选）',
    description: '中国华能集团电子招投标系统发布华能清能院钙钛矿光伏组件设备招标中标结果。招标编号：HNZB2025-03-1-110。中标结果：标段1（HNZB2025-03-1-110-01）中标人：杭州纤纳光电科技股份有限公司，中标金额135万元；标段2（HNZB2025-03-1-110-02）中标人：极电光能有限公司，中标金额141万元；标段3（HNZB2025-03-1-110-03）中标人：仁烁光粒（苏州）有限公司，中标金额75.6万元。招标人：中国华能集团清洁能源技术研究院有限公司。',
    projectType: 'procurement',
    budget: '351.6万元（三标段合计）',
    region: '北京市',
    publisherName: '中国华能集团清洁能源技术研究院有限公司',
    contactInfo: '招标代理：中国华能集团有限公司北京招标分公司；联系人：薛女士，电话：010-81917692',
    sourceUrl: 'http://m.solarzoom.com/article-192818-1.html',
    sourcePlatform: 'SOLARZOOM光储亿家',
    isImportant: true,
    status: 'awarded',
    publishedAt: new Date('2025-04-27'),
  },
  {
    title: '华能清能院钙钛矿电池耗材招标公告',
    description: '华能清能院钙钛矿电池耗材招标公告（招标编号：HNZB2026-01-1-070）。本项目已由项目审批机关批准，项目资金为企业自筹，招标人为中国华能集团清洁能源技术研究院有限公司。本项目已具备招标条件，现进行公开招标，欢迎符合条件的投标人参与投标。',
    projectType: 'procurement',
    budget: '未披露',
    region: '北京市',
    publisherName: '中国华能集团清洁能源技术研究院有限公司',
    contactInfo: '招标编号：HNZB2026-01-1-070',
    sourceUrl: 'https://www.bidcenter.com.cn/zhaobiao/zbkeyw-29082.html',
    sourcePlatform: '采招网',
    isImportant: true,
    status: 'open',
    publishedAt: new Date('2026-01-10'),
  },
  {
    title: '国家光伏储能实证实验平台（大庆基地）四期钙钛矿电池组件采购（极电光能中标）',
    description: '国家电力投资集团国家光伏、储能实证实验平台（大庆基地）四期光伏项目电池组件采购项目中标结果公示。极电光能中标，采购钙钛矿光伏电池组件（2.81m²大面积组件）。该项目是国家级光伏实证平台的重要组成部分，将对钙钛矿组件进行长期实证测试。',
    projectType: 'procurement',
    budget: '未披露',
    region: '黑龙江省大庆市',
    publisherName: '国家电力投资集团有限公司',
    contactInfo: '国家光伏、储能实证实验平台（大庆基地）',
    sourceUrl: 'https://www.bidcenter.com.cn/zhaobiao/zbkeyw-29082.html',
    sourcePlatform: '采招网',
    isImportant: true,
    status: 'awarded',
    publishedAt: new Date('2026-01-22'),
  },
  {
    title: '捷佳伟创中标航天央企300mm×300mm卫星用钙钛矿-晶硅叠层组件整线',
    description: '捷佳伟创中标航天央企（航天科技/科工体系，低轨卫星星座项目）300mm×300mm卫星用钙钛矿-晶硅叠层组件整线（研发+量产一体化）。核心为低轨卫星星座配套轻量化、高比功率能源系统。组件规格：300mm×300mm叠层组件，柔性基底，可弯曲适配卫星曲面；性能目标：比功率23W/g，效率目标29%+，抗辐照+真空环境下稳定工作5年+。交付周期：2026年Q1-Q2分批交付，2026年Q3完成调试并投产。',
    projectType: 'procurement',
    budget: '未披露（整线毛利率45%+）',
    region: '全国',
    publisherName: '航天科技/航天科工体系央企',
    contactInfo: '中标单位：捷佳伟创（SZ300724）',
    sourceUrl: 'https://caifuhao.eastmoney.com/news/20260113161238845377470',
    sourcePlatform: '东方财富财富号',
    isImportant: true,
    status: 'awarded',
    publishedAt: new Date('2025-11-01'),
  },
  {
    title: '高效钙钛矿薄膜太阳电池中试线项目国际招标（合肥京东方）',
    description: '中电商务（北京）有限公司受合肥京东方光能科技有限公司委托，对高效钙钛矿薄膜太阳电池中试线项目进行国际公开竞争性招标。招标编号：4197-244HFBOEST02/19。项目实施地点：中国安徽省合肥市新站区铜陵北路3166号1号楼。招标文件售价：人民币1500元/美元250元。投标截止时间：2024年11月14日10:00（北京时间）。',
    projectType: 'construction',
    budget: '未披露',
    region: '安徽省合肥市',
    publisherName: '合肥京东方光能科技有限公司',
    contactInfo: '招标代理：中电商务（北京）有限公司，联系人：刘经理（010-52200340），鞠经理（010-52200328）',
    sourceUrl: 'https://chinabidding.mofcom.gov.cn/bidDetail/bidding/bulletin/202410/ff80808191b75f330192bc50283055c4.html',
    sourcePlatform: '中国国际招标网（商务部）',
    isImportant: true,
    status: 'closed',
    publishedAt: new Date('2024-10-24'),
    deadline: new Date('2024-11-14'),
  },
  {
    title: '中国乐凯集团钙钛矿电池样品检测询比采购',
    description: '中国乐凯集团有限公司发布钙钛矿光伏电池组件样品检测采购公告。采购编号：XJ026011201069，采购方式：询比采购，业务类型：通用服务采购。报价时间：2026年1月12日17:50至2026年1月19日17:50。',
    projectType: 'service',
    budget: '未披露',
    region: '北京市',
    publisherName: '中国乐凯集团有限公司',
    contactInfo: '采购编号：XJ026011201069',
    sourceUrl: 'https://www.bidcenter.com.cn/zhaobiao/zbkeyw-29082.html',
    sourcePlatform: '采招网',
    isImportant: false,
    status: 'closed',
    publishedAt: new Date('2026-01-12'),
    deadline: new Date('2026-01-19'),
  },
  {
    title: '中石油深圳新能源研究院钙钛矿电池制备及测试系统招标',
    description: '中石油深圳新能源研究院有限公司发布验平台建设（三期）钙钛矿电池制备及测试系统招标采购公告。招标代理机构：中国石油物资公司。开标日期：2025年9月11日09:30。本项目为中石油深圳新能源研究院钙钛矿光伏研究实验平台三期建设的核心设备采购。',
    projectType: 'procurement',
    budget: '未披露',
    region: '广东省深圳市',
    publisherName: '中石油深圳新能源研究院有限公司',
    contactInfo: '招标代理：中国石油物资公司',
    sourceUrl: 'https://www.bidcenter.com.cn/zhaobiao/zbkeyw-29082.html',
    sourcePlatform: '采招网',
    isImportant: false,
    status: 'closed',
    publishedAt: new Date('2025-08-20'),
    deadline: new Date('2025-09-11'),
  },
  {
    title: '大唐海南文昌翁田光伏钙钛矿电池特性逆变器研发及实证项目采购',
    description: '大唐（海南）新能源开发有限公司发布文昌翁田光伏钙钛矿电池特性逆变器研发及实证项目直接采购公告。采购单编号：P-DY-25-00001806。本项目旨在研发适配钙钛矿电池特性的分布式光伏逆变器，并在文昌翁田100MW光伏项目中进行实证研究。合同编号：CDTHT20250101251。',
    projectType: 'research',
    budget: '未披露',
    region: '海南省文昌市',
    publisherName: '大唐（海南）新能源开发有限公司',
    contactInfo: '采购单编号：P-DY-25-00001806；采购代理：中国大唐集团科学技术研究总院有限公司',
    sourceUrl: 'https://www.bidcenter.com.cn/zhaobiao/zbkeyw-29082.html',
    sourcePlatform: '采招网',
    isImportant: false,
    status: 'awarded',
    publishedAt: new Date('2025-06-15'),
  },
  {
    title: '东方电气集团钙钛矿电池技术专利导航服务采购（智慧芽中标）',
    description: '东方电气集团科学技术研究院有限公司发布钙钛矿电池技术专利导航服务采购公告（采购项目编号：DEC1013X202500207）。中标单位：智慧芽信息科技（苏州）有限公司。本项目旨在对钙钛矿电池技术领域进行专利导航分析，支撑东方电气在钙钛矿领域的技术研发布局。',
    projectType: 'service',
    budget: '未披露',
    region: '四川省成都市',
    publisherName: '东方电气集团科学技术研究院有限公司',
    contactInfo: '联系人：白经理，电话：028-87898162',
    sourceUrl: 'https://www.bidcenter.com.cn/zhaobiao/zbkeyw-29082.html',
    sourcePlatform: '采招网',
    isImportant: false,
    status: 'awarded',
    publishedAt: new Date('2025-07-10'),
  },
  {
    title: '中国大唐华东院大面积高性能钙钛矿电池组件稳定性提升服务询比采购',
    description: '中国大唐集团科学技术研究总院有限公司华东电力试验研究院发布大面积高性能钙钛矿电池组件稳定性提升服务询比采购公告。报价截止时间：2025年9月24日17:00，报价有效期至2025年12月18日。组织形式：委托采购。本项目旨在提升大面积钙钛矿电池组件在实际应用中的稳定性，推动钙钛矿组件产业化进程。',
    projectType: 'research',
    budget: '未披露',
    region: '上海市',
    publisherName: '中国大唐集团科学技术研究总院有限公司华东电力试验研究院',
    contactInfo: '报价截止：2025-09-24 17:00',
    sourceUrl: 'https://www.bidcenter.com.cn/zhaobiao/zbkeyw-29082.html',
    sourcePlatform: '采招网',
    isImportant: false,
    status: 'closed',
    publishedAt: new Date('2025-09-10'),
    deadline: new Date('2025-09-24'),
  },
  {
    title: '中国大唐华东院钙钛矿电池组件串联及并联方案研究服务询比采购',
    description: '中国大唐集团科学技术研究总院有限公司华东电力试验研究院发布钙钛矿电池组件串联及并联方案研究服务询比采购公告。报价截止时间：2025年9月24日17:00，报价有效期至2025年12月18日。组织形式：委托采购。本项目旨在研究钙钛矿电池组件的最优串并联方案，为大规模光伏电站的系统集成提供技术支撑。',
    projectType: 'research',
    budget: '未披露',
    region: '上海市',
    publisherName: '中国大唐集团科学技术研究总院有限公司华东电力试验研究院',
    contactInfo: '报价截止：2025-09-24 17:00',
    sourceUrl: 'https://www.bidcenter.com.cn/zhaobiao/zbkeyw-29082.html',
    sourcePlatform: '采招网',
    isImportant: false,
    status: 'closed',
    publishedAt: new Date('2025-09-10'),
    deadline: new Date('2025-09-24'),
  },
  {
    title: '河南大学钙钛矿光电器件平台科研设备采购意向发布',
    description: '河南大学发布钙钛矿光电器件平台搭建科研设备采购意向公告。需求概况：钙钛矿光电器件平台搭建主要是为加快高性能钙钛矿光伏器件的研发与测试，拟采购一批相关科研仪器设备，包括钙钛矿薄膜制备、表征、测试等核心设备。发布平台：河南省政府采购网。',
    projectType: 'procurement',
    budget: '未披露',
    region: '河南省开封市',
    publisherName: '河南大学',
    contactInfo: '河南省政府采购网',
    sourceUrl: 'https://mguangfu.bjx.com.cn/topics/gaitaikuang/',
    sourcePlatform: '北极星太阳能光伏网',
    isImportant: false,
    status: 'open',
    publishedAt: new Date('2025-11-21'),
  },
  {
    title: '四川融创中心钙钛矿异质结科技成果转化中试基地项目招标',
    description: '四川融创中心发布钙钛矿异质结科技成果转化中试基地项目招标公告，采用EPC工程总承包模式，包括勘察、设计、采购及施工等全过程的管理及组织实施。项目旨在建设钙钛矿/异质结叠层电池的中试生产基地，推动科技成果产业化转化。',
    projectType: 'construction',
    budget: '未披露',
    region: '四川省',
    publisherName: '四川融创中心',
    contactInfo: 'EPC工程总承包',
    sourceUrl: 'https://mguangfu.bjx.com.cn/topics/gaitaikuang/',
    sourcePlatform: '北极星太阳能光伏网',
    isImportant: false,
    status: 'open',
    publishedAt: new Date('2025-10-15'),
  },
  {
    title: '深圳大学蒸镀型钙钛矿电池真空蒸镀仪采购招标',
    description: '深圳大学发布蒸镀型钙钛矿电池真空蒸镀仪招标项目公告。潜在投标人应在深圳市加乐咨询有限公司获取招标文件，并于2024年10月22日9:30（北京时间）前递交投标文件。本设备用于深圳大学钙钛矿太阳能电池研究实验室，支撑蒸镀型钙钛矿电池的制备研究。',
    projectType: 'procurement',
    budget: '未披露',
    region: '广东省深圳市',
    publisherName: '深圳大学',
    contactInfo: '招标代理：深圳市加乐咨询有限公司',
    sourceUrl: 'https://bidding.szu.edu.cn/info/1017/32021.htm',
    sourcePlatform: '深圳大学招投标管理中心',
    isImportant: false,
    status: 'closed',
    publishedAt: new Date('2024-10-10'),
    deadline: new Date('2024-10-22'),
  },
  {
    title: '上海大学钙钛矿电池制备和测试平台项目中标结果公告',
    description: '上海大学钙钛矿电池制备和测试平台项目完成采购并公示中标结果。采购人：上海大学（地址：上大路99号A楼502室，联系方式：021-66135586）。采购代理机构：上海政采项目管理有限公司。本平台将支撑上海大学在钙钛矿光伏领域的基础研究和应用研究。',
    projectType: 'procurement',
    budget: '未披露',
    region: '上海市',
    publisherName: '上海大学',
    contactInfo: '联系方式：021-66135586；采购代理：上海政采项目管理有限公司',
    sourceUrl: 'https://bidding.shu.edu.cn/ywsp/lcpz/fjgl_downLoad.jsp?wid=202411010026942317',
    sourcePlatform: '上海大学招投标管理平台',
    isImportant: false,
    status: 'awarded',
    publishedAt: new Date('2024-11-01'),
  },
  {
    title: '中国电建华能青海钙钛矿多元互证实证基地汇流箱采购（终止公告）',
    description: '中国电建水电十局一分局华能青海分公司发布钙钛矿多元互证实证基地项目施工总承包工程项目汇流箱采购项目终止公告。招标项目编号：POWERCHINA-0110-250265。本项目为华能青海分公司钙钛矿多元互证实证基地建设的配套设备采购，因故终止本次招标，后续将重新组织采购。',
    projectType: 'procurement',
    budget: '未披露',
    region: '青海省',
    publisherName: '中国电建水电十局一分局华能青海分公司',
    contactInfo: '招标编号：POWERCHINA-0110-250265',
    sourceUrl: 'https://bid.powerchina.cn/notice/detail?id=2409301647',
    sourcePlatform: '中国电建阳光采购网',
    isImportant: false,
    status: 'cancelled',
    publishedAt: new Date('2025-06-10'),
  },
  {
    title: '华能清能院钙钛矿电池及组件IV性能和双85检测采购（无锡检测院中标）',
    description: '华能清能院钙钛矿电池及组件IV性能和双85检测采购结果公告（采购项目编号：HNFZ2025-08-1-00011）。通过询比采购，经采购小组综合评定，成交供应商：无锡市检验检测认证研究院，成交金额：251,600.00元。本项目对钙钛矿电池及组件进行IV性能测试和双85（85℃/85%RH）耐候性检测。',
    projectType: 'service',
    budget: '25.16万元',
    region: '北京市',
    publisherName: '中国华能集团清洁能源技术研究院有限公司',
    contactInfo: '采购项目编号：HNFZ2025-08-1-00011；中标单位：无锡市检验检测认证研究院',
    sourceUrl: 'https://www.bidcenter.com.cn/zhaobiao/zbkeyw-29082.html',
    sourcePlatform: '采招网',
    isImportant: false,
    status: 'awarded',
    publishedAt: new Date('2025-08-25'),
  },
  {
    title: '钙钛矿太阳能电池结晶动力学、钝化及仿真技术研究项目招标',
    description: '钙钛矿太阳能电池结晶动力学、钝化及仿真技术研究项目招标公告（招标编号：ZY25-SH17-FW12）。本项目旨在研究钙钛矿薄膜的结晶动力学机制、界面钝化策略及器件仿真技术，为提升钙钛矿电池效率和稳定性提供理论与技术支撑。',
    projectType: 'research',
    budget: '未披露',
    region: '上海市',
    publisherName: '未披露（招标编号ZY25-SH17-FW12）',
    contactInfo: '招标编号：ZY25-SH17-FW12',
    sourceUrl: 'https://www.bidcenter.com.cn/zhaobiao/zbkeyw-29082.html',
    sourcePlatform: '采招网',
    isImportant: false,
    status: 'open',
    publishedAt: new Date('2025-07-20'),
  },
  {
    title: '深圳羲和光能2MW印刷式碳基钙钛矿电池合作开发中试产线项目备案',
    description: '深圳羲和光能有限公司2MW印刷式碳基钙钛矿电池合作开发中试产线项目完成企业投资项目备案（国家编码：2509-440311-04-01-671670，立项类型：备案，立项时间：2025-09-09）。本项目将建设2MW规模的印刷式碳基钙钛矿电池中试产线，采用低成本碳电极替代贵金属电极，推动钙钛矿电池降本增效。',
    projectType: 'construction',
    budget: '未披露',
    region: '广东省深圳市',
    publisherName: '深圳羲和光能有限公司',
    contactInfo: '国家编码：2509-440311-04-01-671670',
    sourceUrl: 'https://www.bidcenter.com.cn/zhaobiao/zbkeyw-29082.html',
    sourcePlatform: '采招网',
    isImportant: false,
    status: 'open',
    publishedAt: new Date('2025-09-09'),
  },
];

// 插入数据
for (const t of tenders) {
  const cols = ['title','description','projectType','budget','region','publisherName','contactInfo','sourceUrl','sourcePlatform','isImportant','status','publishedAt'];
  const vals = cols.map(c => t[c] !== undefined ? t[c] : null);
  if (t.deadline) {
    cols.push('deadline');
    vals.push(t.deadline);
  }
  const placeholders = cols.map(() => '?').join(',');
  await conn.query(`INSERT INTO tenders (${cols.join(',')}) VALUES (${placeholders})`, vals);
  console.log('Inserted:', t.title.substring(0, 50));
}

const [countRows] = await conn.query('SELECT COUNT(*) as cnt FROM tenders');
console.log('\nTotal tenders inserted:', countRows[0].cnt);

await conn.end();
console.log('Done!');
