/**
 * Seed data for perovskite solar cell efficiency records
 * Sources:
 * - NREL Best Research-Cell Efficiency Chart (https://www.nrel.gov/pv/cell-efficiency.html)
 * - Fluxim Perovskite Efficiency Records (https://www.fluxim.com/research-blogs/perovskite-silicon-tandem-pv-record-updates)
 * - Solar Cell Efficiency Tables (Green et al., Progress in Photovoltaics)
 * - Published papers and certified records
 */

export const efficiencySeedData = [
  // ===== SINGLE-JUNCTION PEROVSKITE =====
  {
    cellType: "单结钙钛矿",
    efficiency: 3.8,
    year: 2009,
    institution: "Miyasaka Group (Japan)",
    country: "日本",
    certifiedBy: "未认证",
    area: 0.38,
    notes: "首个钙钛矿太阳能电池，Miyasaka等人报道，液态电解质，稳定性差",
    source: "Kojima et al., JACS 2009",
    isWorldRecord: false,
  },
  {
    cellType: "单结钙钛矿",
    efficiency: 6.5,
    year: 2011,
    institution: "Park Group (Korea)",
    country: "韩国",
    certifiedBy: "未认证",
    area: 0.285,
    notes: "Park等人改进，仍为液态电解质",
    source: "Im et al., Nanoscale 2011",
    isWorldRecord: false,
  },
  {
    cellType: "单结钙钛矿",
    efficiency: 10.9,
    year: 2012,
    institution: "EPFL / Snaith Group (Oxford)",
    country: "瑞士/英国",
    certifiedBy: "未认证",
    area: 0.076,
    notes: "固态钙钛矿电池突破，Snaith等人报道，开创固态钙钛矿时代",
    source: "Lee et al., Science 2012",
    isWorldRecord: true,
  },
  {
    cellType: "单结钙钛矿",
    efficiency: 15.0,
    year: 2013,
    institution: "EPFL (Grätzel Group)",
    country: "瑞士",
    certifiedBy: "未认证",
    area: 0.16,
    notes: "EPFL Grätzel团队，介孔结构钙钛矿电池",
    source: "Burschka et al., Nature 2013",
    isWorldRecord: true,
  },
  {
    cellType: "单结钙钛矿",
    efficiency: 17.9,
    year: 2014,
    institution: "KRICT/UNIST (Korea)",
    country: "韩国",
    certifiedBy: "NREL",
    area: 0.096,
    notes: "韩国KRICT/UNIST，首次NREL认证突破",
    source: "Yang et al., Science 2015",
    isWorldRecord: true,
  },
  {
    cellType: "单结钙钛矿",
    efficiency: 20.1,
    year: 2015,
    institution: "KRICT (Korea)",
    country: "韩国",
    certifiedBy: "NREL",
    area: 0.096,
    notes: "突破20%效率大关，NREL认证",
    source: "NREL Efficiency Table",
    isWorldRecord: true,
  },
  {
    cellType: "单结钙钛矿",
    efficiency: 22.1,
    year: 2016,
    institution: "KRICT/UNIST (Korea)",
    country: "韩国",
    certifiedBy: "NREL",
    area: 0.094,
    notes: "效率持续提升，NREL认证",
    source: "NREL Efficiency Table v8",
    isWorldRecord: true,
  },
  {
    cellType: "单结钙钛矿",
    efficiency: 23.3,
    year: 2018,
    institution: "KRICT (Korea)",
    country: "韩国",
    certifiedBy: "NREL",
    area: 0.0937,
    notes: "NREL认证，稳态效率",
    source: "NREL Efficiency Table v52",
    isWorldRecord: true,
  },
  {
    cellType: "单结钙钛矿",
    efficiency: 25.2,
    year: 2020,
    institution: "KRICT/MIT (Korea/USA)",
    country: "韩国/美国",
    certifiedBy: "NREL",
    area: 0.0959,
    notes: "NREL认证，突破25%，反式结构",
    source: "NREL Efficiency Table v56",
    isWorldRecord: true,
  },
  {
    cellType: "单结钙钛矿",
    efficiency: 25.7,
    year: 2022,
    institution: "KAUST (Saudi Arabia)",
    country: "沙特阿拉伯",
    certifiedBy: "NREL",
    area: 0.0588,
    notes: "KAUST团队，NREL认证",
    source: "NREL Efficiency Table v60",
    isWorldRecord: true,
  },
  {
    cellType: "单结钙钛矿",
    efficiency: 26.1,
    year: 2023,
    institution: "EPFL (Switzerland)",
    country: "瑞士",
    certifiedBy: "NREL",
    area: 0.0588,
    notes: "EPFL团队，NREL认证",
    source: "NREL Efficiency Table v62",
    isWorldRecord: true,
  },
  {
    cellType: "单结钙钛矿",
    efficiency: 26.7,
    year: 2024,
    institution: "USTC (中国科技大学)",
    country: "中国",
    certifiedBy: "NREL",
    area: 0.0588,
    notes: "中国科学技术大学徐集贤团队，NREL认证稳态效率",
    source: "USTC Press Release, Sep 2024",
    isWorldRecord: true,
  },
  {
    cellType: "单结钙钛矿",
    efficiency: 26.95,
    year: 2025,
    institution: "苏州大学/UNSW",
    country: "中国/澳大利亚",
    certifiedBy: "NREL",
    area: 0.0583,
    notes: "苏州大学与澳大利亚新南威尔士大学合作，NREL认证",
    source: "Fluxim 2026 Update",
    isWorldRecord: true,
  },

  // ===== PEROVSKITE/SILICON TANDEM =====
  {
    cellType: "钙钛矿/硅叠层",
    efficiency: 13.7,
    year: 2015,
    institution: "EPFL/CSEM (Switzerland)",
    country: "瑞士",
    certifiedBy: "未认证",
    area: 1.0,
    notes: "首个高效钙钛矿/硅叠层电池报道",
    source: "Löper et al., J. Phys. Chem. Lett. 2015",
    isWorldRecord: false,
  },
  {
    cellType: "钙钛矿/硅叠层",
    efficiency: 21.2,
    year: 2016,
    institution: "IMEC (Belgium)",
    country: "比利时",
    certifiedBy: "未认证",
    area: 0.13,
    notes: "IMEC团队，4端叠层",
    source: "IMEC Press Release 2016",
    isWorldRecord: false,
  },
  {
    cellType: "钙钛矿/硅叠层",
    efficiency: 25.2,
    year: 2018,
    institution: "EPFL/CSEM (Switzerland)",
    country: "瑞士",
    certifiedBy: "NREL",
    area: 1.43,
    notes: "NREL认证，2端叠层",
    source: "Sahli et al., Nature Materials 2018",
    isWorldRecord: true,
  },
  {
    cellType: "钙钛矿/硅叠层",
    efficiency: 29.1,
    year: 2020,
    institution: "HZB (Germany)",
    country: "德国",
    certifiedBy: "Fraunhofer ISE",
    area: 1.08,
    notes: "亥姆霍兹柏林研究中心，Fraunhofer认证",
    source: "Al-Ashouri et al., Science 2020",
    isWorldRecord: true,
  },
  {
    cellType: "钙钛矿/硅叠层",
    efficiency: 29.8,
    year: 2021,
    institution: "HZB (Germany)",
    country: "德国",
    certifiedBy: "NREL",
    area: 1.08,
    notes: "HZB团队，NREL认证",
    source: "NREL Efficiency Table v58",
    isWorldRecord: true,
  },
  {
    cellType: "钙钛矿/硅叠层",
    efficiency: 32.5,
    year: 2022,
    institution: "HZB (Germany)",
    country: "德国",
    certifiedBy: "NREL",
    area: 1.0,
    notes: "HZB突破32%，纳米织构界面，NREL认证",
    source: "Helmholtz-Zentrum Berlin Press Release 2022",
    isWorldRecord: true,
  },
  {
    cellType: "钙钛矿/硅叠层",
    efficiency: 33.7,
    year: 2023,
    institution: "KAUST/NREL (Saudi Arabia/USA)",
    country: "沙特阿拉伯/美国",
    certifiedBy: "NREL",
    area: 1.0,
    notes: "KAUST与NREL合作，NREL认证",
    source: "NREL Efficiency Table v62",
    isWorldRecord: true,
  },
  {
    cellType: "钙钛矿/硅叠层",
    efficiency: 33.9,
    year: 2023,
    institution: "隆基绿能 (LONGi Solar)",
    country: "中国",
    certifiedBy: "NREL",
    area: 1.0,
    notes: "隆基绿能，NREL认证，2023年11月",
    source: "LONGi Press Release Nov 2023",
    isWorldRecord: true,
  },
  {
    cellType: "钙钛矿/硅叠层",
    efficiency: 34.6,
    year: 2024,
    institution: "隆基绿能 (LONGi Solar)",
    country: "中国",
    certifiedBy: "NREL",
    area: 1.0,
    notes: "隆基绿能，NREL认证，2024年6月SNEC发布",
    source: "LONGi Press Release Jun 2024",
    isWorldRecord: true,
  },
  {
    cellType: "钙钛矿/硅叠层",
    efficiency: 34.85,
    year: 2025,
    institution: "隆基绿能 (LONGi Solar)",
    country: "中国",
    certifiedBy: "NREL",
    area: 1.0,
    notes: "隆基绿能，NREL认证，2025年4月，当前世界纪录",
    source: "LONGi Press Release Apr 2025",
    isWorldRecord: true,
  },

  // ===== ALL-PEROVSKITE TANDEM =====
  {
    cellType: "全钙钛矿叠层",
    efficiency: 20.3,
    year: 2018,
    institution: "EPFL (Switzerland)",
    country: "瑞士",
    certifiedBy: "未认证",
    area: 0.049,
    notes: "首个高效全钙钛矿叠层电池",
    source: "Eperon et al., Science 2016 (updated 2018)",
    isWorldRecord: false,
  },
  {
    cellType: "全钙钛矿叠层",
    efficiency: 24.8,
    year: 2020,
    institution: "Nanjing University (China)",
    country: "中国",
    certifiedBy: "未认证",
    area: 0.049,
    notes: "南京大学谭海仁团队",
    source: "Lin et al., Science 2020",
    isWorldRecord: true,
  },
  {
    cellType: "全钙钛矿叠层",
    efficiency: 26.4,
    year: 2021,
    institution: "Nanjing University (China)",
    country: "中国",
    certifiedBy: "JET",
    area: 0.049,
    notes: "南京大学，JET认证",
    source: "Tong et al., Science 2022",
    isWorldRecord: true,
  },
  {
    cellType: "全钙钛矿叠层",
    efficiency: 28.0,
    year: 2022,
    institution: "仁烁光能/南京大学",
    country: "中国",
    certifiedBy: "JET",
    area: 0.049,
    notes: "仁烁光能与南京大学合作，JET认证",
    source: "Renshine Press Release 2022",
    isWorldRecord: true,
  },
  {
    cellType: "全钙钛矿叠层",
    efficiency: 29.0,
    year: 2023,
    institution: "仁烁光能/南京大学",
    country: "中国",
    certifiedBy: "JET",
    area: 0.049,
    notes: "仁烁光能，JET认证，2023年1月",
    source: "Renshine Press Release Jan 2023",
    isWorldRecord: true,
  },
  {
    cellType: "全钙钛矿叠层",
    efficiency: 29.4,
    year: 2023,
    institution: "仁烁光能/南京大学",
    country: "中国",
    certifiedBy: "NREL",
    area: 0.049,
    notes: "仁烁光能，NREL认证",
    source: "NREL Efficiency Table v62",
    isWorldRecord: true,
  },
  {
    cellType: "全钙钛矿叠层",
    efficiency: 30.1,
    year: 2024,
    institution: "仁烁光能/南京大学",
    country: "中国",
    certifiedBy: "NREL",
    area: 0.049,
    notes: "仁烁光能与南京大学合作，NREL认证，2024年世界纪录",
    source: "Renshine/NJU Press Release 2024",
    isWorldRecord: true,
  },

  // ===== FLEXIBLE PEROVSKITE =====
  {
    cellType: "柔性钙钛矿",
    efficiency: 12.0,
    year: 2015,
    institution: "EPFL (Switzerland)",
    country: "瑞士",
    certifiedBy: "未认证",
    area: 0.16,
    notes: "首个高效柔性钙钛矿电池",
    source: "Roldan-Carmona et al., Energy Environ. Sci. 2015",
    isWorldRecord: false,
  },
  {
    cellType: "柔性钙钛矿",
    efficiency: 19.1,
    year: 2019,
    institution: "ISCAS (China)",
    country: "中国",
    certifiedBy: "未认证",
    area: 0.049,
    notes: "中国科学院半导体研究所",
    source: "Zhao et al., Joule 2019",
    isWorldRecord: true,
  },
  {
    cellType: "柔性钙钛矿",
    efficiency: 23.0,
    year: 2021,
    institution: "Nanjing University (China)",
    country: "中国",
    certifiedBy: "未认证",
    area: 0.049,
    notes: "南京大学，超薄柔性基底",
    source: "Li et al., Nature 2021",
    isWorldRecord: true,
  },
  {
    cellType: "柔性钙钛矿",
    efficiency: 24.4,
    year: 2023,
    institution: "KAUST (Saudi Arabia)",
    country: "沙特阿拉伯",
    certifiedBy: "NREL",
    area: 0.049,
    notes: "KAUST团队，NREL认证",
    source: "NREL Efficiency Table v62",
    isWorldRecord: true,
  },
  {
    cellType: "柔性钙钛矿",
    efficiency: 25.0,
    year: 2024,
    institution: "LONGi/Nanjing University",
    country: "中国",
    certifiedBy: "NREL",
    area: 0.049,
    notes: "隆基绿能与南京大学合作，超薄晶硅-钙钛矿叠层，Nature发表",
    source: "LONGi Nature Paper Nov 2025",
    isWorldRecord: true,
  },

  // ===== PEROVSKITE MODULE =====
  {
    cellType: "钙钛矿组件",
    efficiency: 12.1,
    year: 2016,
    institution: "Microquanta (China)",
    country: "中国",
    certifiedBy: "NREL",
    area: 17.28,
    notes: "纤纳光电，首个大面积钙钛矿组件NREL认证",
    source: "NREL Efficiency Table",
    isWorldRecord: true,
  },
  {
    cellType: "钙钛矿组件",
    efficiency: 16.1,
    year: 2020,
    institution: "Microquanta (China)",
    country: "中国",
    certifiedBy: "NREL",
    area: 703.0,
    notes: "纤纳光电，大面积组件",
    source: "NREL Efficiency Table v56",
    isWorldRecord: true,
  },
  {
    cellType: "钙钛矿组件",
    efficiency: 17.18,
    year: 2022,
    institution: "Microquanta (China)",
    country: "中国",
    certifiedBy: "NREL",
    area: 7200.0,
    notes: "纤纳光电，0.72m²大面积组件，NREL认证",
    source: "IOPscience Review 2024",
    isWorldRecord: true,
  },
  {
    cellType: "钙钛矿组件",
    efficiency: 17.2,
    year: 2024,
    institution: "南京大学/仁烁光能",
    country: "中国",
    certifiedBy: "NREL",
    area: 7200.0,
    notes: "南京大学与仁烁光能合作，NREL认证，2024年商业组件效率世界纪录",
    source: "NJU Press Release Dec 2025",
    isWorldRecord: true,
  },
];

export const totalEfficiencyRecords = efficiencySeedData.length;
